apiVersion: v1
kind: Service
metadata:
  labels:
    app: hry
    tenant: tenant-test1
  name: hry-service
  namespace: tenant-test1
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hry
    tenant: tenant-test1
  type: ClusterIP
