apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: tenant-a
  labels:
    app: nginx
    tenant: tenant-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tenant: tenant-a
  template:
    metadata:
      labels:
        app: nginx
        tenant: tenant-a
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
